---
  server:
    description: "The url to the JIRA"
    type: "string"
    required: true
    secret: false
  access_token:
    description: "The access token"
    type: "string"
    required: true
    secret: false
  access_token_secret:
    description: "The access token secret"
    type: "string"
    required: true
    secret: true
  consumer_key:
    description: "The consumer key"
    type: "string"
    required: true
    secret: true
  key_cert_path:
    description: "The path to the certificate key"
    type: "string"
    required: true
    secret: false
  attachment_dir:
    description: "The path of the downloaded attachments, default /tmp"
    type: "string"
    required: false
    secret: false