name: applicationlinks
runner_type: run-python
enabled: true
entry_point: lib/applicationlinks.py
description: "List of application links"
parameters:
  <td class="field-body">json</td>:
    type: string
    description: ""
    required: false
